### ISSUE TITLE
Always crashing on a certain wordpress page

### ISSUE THREAD

**Issue by morituri2** [Mitch528/WebNovelConverter#1]
Hi,
webnovelconverter doesn't work on https://putttytranslations.wordpress.com/got-toc/
It can retrieve the links but shortly after starting the converter-process the program stops working.

**Comment by Mitch528** [comment]
Fixed in 0828399f4e3a79fb860b64e84a8c270d80b657ec

You can get the latest version [here](https://s3.amazonaws.com/webnovels/WebNovelConverter.zip).

**Comment by morituri2** [comment]
Thanks. That was fast :+1: :)

**Comment by Mitch528** [comment]
No problem, thanks for the bug report!
