### ISSUE TITLE
unable to read TOC on grimgarthetranslation.wordpress.com

### ISSUE THREAD

**Issue by TheOne320** [Mitch528/WebNovelConverter#10]
Trying to retrieve the toc for https://grimgarthetranslation.wordpress.com/level-2/ returns nothing.

**Comment by Mitch528** [comment]
Fixed in c8cd512f5cca1e6285cc5d30450453d884757ee0

**Comment by TheOne320** [comment]
It can read the toc, but does not download the chapters. The resulting epub just contains a few comments.

**Comment by Mitch528** [comment]
I'll take a look.

**Comment by Mitch528** [comment]
Should be fixed now. Let me know if you encounter any more issues.
