### ISSUE TITLE
Crash on translationnations.com

### ISSUE THREAD

**Issue by morituri2** [Mitch528/WebNovelConverter#12]
Version 1.4.4 crashs on [translationnations.com](http://www.translationnations.com/translations/limitless-sword-god/) using "Table of Contents"-Mode (Wordpress)

"Next Chapter"-Mode also doesn't work but the program does not crash: [Translationnations.com](http://www.translationnations.com/translations/limitless-sword-god/lsg-chapter-0001/)

**Comment by Mitch528** [comment]
Fixed.

For some reason, translationnations.com is returning a 500 (Internal Server Error) for all requests, even though it displays correctly.
