### ISSUE TITLE
Crash on royalroadl.com

### ISSUE THREAD

**Issue by Septimus412** [Mitch528/WebNovelConverter#2]
hi,
first thanks for this software it's pretty cool
next i want to report a crash on http://royalroadl.com/fiction/3937

i'm counting on you ^^

Thanks

**Comment by Mitch528** [comment]
Fixed in 8981e0e7e0e3c02ec9b0571bcdd22ffe2b7b0e4f

You can download the new version [here](https://s3.amazonaws.com/webnovels/WebNovelConverter.zip).

**Comment by Septimus412** [comment]
ok thanks

ps: it work for me too ; )
