### ISSUE TITLE
RoyalRoadL New Game Plus missing content

### ISSUE THREAD

**Issue by TheOne320** [Mitch528/WebNovelConverter#3]
So when downloading New Game Plus (http://royalroadl.com/fiction/3041), some chapters are just empty. For example chapter 6 and chapter 10.

**Comment by Mitch528** [comment]
Thanks for the bug report!

Fixed in d14d1f3f87c75baa1f18c1368657587b8bd9d369

You can download the new version [here](https://s3.amazonaws.com/webnovels/WebNovelConverter.zip).
