### ISSUE TITLE
RoyalRoadL Re:Ocean missing RPG style boxes

### ISSUE THREAD

**Issue by TheOne320** [Mitch528/WebNovelConverter#4]
In Re:Ocean (http://royalroadl.com/fiction/1014) there are rpg style pop-up boxes that are part of the story (e.g. chapter 1). These boxes are missing in the created epub file.

**Comment by Mitch528** [comment]
Thanks for the bug report!

Fixed in d14d1f3f87c75baa1f18c1368657587b8bd9d369

You can download the new version [here](https://s3.amazonaws.com/webnovels/WebNovelConverter.zip).
