### ISSUE TITLE
bug royalroadl.com

### ISSUE THREAD

**Issue by Septimus412** [Mitch528/WebNovelConverter#5]
hi, it's me again

well, WebNovelConverter do work on royalroadl.com now but it don't pick the coloured words and the tabs, 
exemple :  (http://royalroadl.com/forum/showthread.php?tid=48721)

I decided that since I've worked so hard to take a break today. One thing I haven't done is use my [[shape shift]] forms a lot. I've never had a use for turning into a mouse or a fox. Ram seems useful but I don't have it yet. So today I'll turn into a mouse and [[sneak]] around spying on everyone. 
[[coloured word]]

become : 
I decided that since I've worked so hard to take a break today. One thing I haven't done is use my  forms a lot. I've never had a use for turning into a mouse or a fox. Ram seems useful but I don't have it yet. So today I'll turn into a mouse and  around spying on everyone. 

Same for tabs that disappear

Thanks in advance

**Comment by Mitch528** [comment]
Thanks for the bug report!

Fixed in d14d1f3f87c75baa1f18c1368657587b8bd9d369

You can download the new version [here](https://s3.amazonaws.com/webnovels/WebNovelConverter.zip).
