### ISSUE TITLE
Bug report on http://dragomircm.com/wn1/

### ISSUE THREAD

**Issue by Septimus412** [Mitch528/WebNovelConverter#6]
Hi,
when i try to retrieve the ToC of http://dragomircm.com/wn1/ , I do get an epub but with nothing inside except the titles.

Thanks for your hard work

**Comment by Mitch528** [comment]
Thanks for the bug report!

Fixed in 22b3a28b957200daf5958a04da3270471bcfefe4

You can download the new version [here](https://s3.amazonaws.com/webnovels/WebNovelConverter.zip).
