### ISSUE TITLE
Pdf and some feedback

### ISSUE THREAD

**Issue by Kichiro77** [Mitch528/WebNovelConverter#7]
Hi, thanks for this awesome program.
Is there any way to save file as .pdf? it only show me .epub option as output type. Also can you make it possible to download from http://storiesonline.net/home.php as well? that will be great. http://wuxiaworld.com  is not working anymore btw.

It will be also great if it can select links together to move into links to ignore like select chapter 1~300 to ignored ones, download 301-600 without ticking them 1 by 1 and the opposite from ignore to download. Though this is only important in big novels.

   About table of content some times authors/translators don't update it or do it once in a while can you make it so it can download those chapters which are not in toc without doing it manually 1 by 1 as well? maybe optional option.

This is just some feedback to make it even more perfect, It is already very much amazing and very easy to use. Thank you very much for your hard work!

**Comment by Mitch528** [comment]
Hey, thanks for the feedback!

Unfortunately, I removed the pdf option in a previous version; it relied on a quite large third-party program to do the the processing, so I decided to stop using it. However, you can use [Calibre](http://calibre-ebook.com/) to convert the epubs into pdfs.

I don't think I'll be able to get it to work with the Stories Online website, sorry.

As for Wuxia World, they just recently turned on CloudFlare which blocks these types of programs, so there's nothing I can do about that.

Actually, it already is possible to move multiple chapters at a time. Just click on a chapter, hold down shift, then click on another chapter down the list; that will select all the chapters between the 1st and last chapter selected.

Yeah, I know that some TOCs aren't always up-to-date. However, I don't really see any way to find the links to the other chapters.

**Comment by Kichiro77** [comment]
Ah i see it was possible to select multiple chapters like that, Thanks a lot and those problems were only minor one now when i look at it again so no worries haha...  i already used it to download a lot of stuff now amazing software~

**Comment by Mitch528** [comment]
Sorry for the late reply,

I'm not quite sure regarding the settings on Calibre. You might just have to experiment and see what works best for you.
