### ISSUE TITLE
Crash sousetsuka.com

### ISSUE THREAD

**Issue by TheOne320** [Mitch528/WebNovelConverter#8]
Crash on http://www.sousetsuka.com/p/blog-page_11.html  when trying to epub chapters 11-16 -> 11-23. Have not tested other combinations.

**Comment by Mitch528** [comment]
Sorry for the late reply,

That website seems to be Blogspot-based, which WebNovelConverter doesn't support just yet. I'll take a look and see if I can add support for Blogspot.

**Comment by Mitch528** [comment]
This should now work in the latest version, let me know if not.

**Comment by TheOne320** [comment]
Issue is resolved.
P.S. Where can I ask questions about WebNovelConverter? I do not want to spam the Issues section.

**Comment by Mitch528** [comment]
I don't really have anywhere else besides here to ask questions. Feel free to make issues with any questions you have.
